### ISSUE TITLE
Faucets crash often

### ISSUE THREAD

**Issue by mutantcornholio** [paritytech/polkadot-testnet-faucet#438]
errors mostly look like
```
/faucet/node_modules/@polkadot-api/substrate-client/dist/index.js:505
        return error ? cb.onError(new RpcError(error)) : cb.onSuccess(result, (opaqueId, subscriber) => {
                                  ^
RpcError: Internal error
    at onMessage (/faucet/node_modules/@polkadot-api/substrate-client/dist/index.js:505:35)
    at /faucet/node_modules/@polkadot-api/json-rpc-provider-proxy/dist/index.js:145:7
    at Array.forEach (<anonymous>)
    at onHalt (/faucet/node_modules/@polkadot-api/json-rpc-provider-proxy/dist/index.js:144:26)
    at /faucet/node_modules/@polkadot-api/json-rpc-provider-proxy/dist/index.js:195:101 {
  code: -32603,
  data: undefined
}
Node.js v22.6.0
```
here's the uptime log
![Screen Shot 2024-09-10 at 16 51 49](https://github.com/user-attachments/assets/080f3770-0c36-46b3-9c99-422710e495ae)

https://github.com/polkadot-api/polkadot-api/issues/710
https://github.com/polkadot-api/polkadot-api/issues/713

**Comment by mutantcornholio** [comment]
We've been good for a while already, closing this issue
